### ISSUE TITLE
Create release tag

### ISSUE THREAD

**Issue by jeebak** [smcameron/wordwarvi#2]
Hi there. I've created a Homebrew Formula for wordwarvi that builds cleanly, but the Homebrew contribution guidelines requires a "v1.2.3" type version number instead of specifying the "master" branch of this repo. I tried using the "wordwarvi-1.00.tar.gz" file from the sourceforge download page but the code there is quite older than what's currently in "master" and would not build under OSX in its current state. At your leisure, could a "v1.2.3" type tag be created? It's be much appreciated.

Thanks!

**Comment by smcameron** [comment]
HI,

I created tag 'v1.0.2' and made the version number the code reports match.

https://github.com/smcameron/wordwarvi/releases

https://github.com/smcameron/wordwarvi/commit/74eb004f45aafb186d6f1ca773082a652d984b1a

-- steve

**Comment by jeebak** [comment]
Most awesome! I'll update if/when the Formula is accepted.

Thanks!

**Comment by jeebak** [comment]
I put in the PR with homebrew here: https://github.com/Homebrew/homebrew/pull/50042 ... but unfortunately, they decided to pass on it.

I put the formula on my on personal homebrew tap, if anybody'd want it: https://github.com/jeebak/homebrew-jeebak/blob/master/Formula/wordwarvi.rb

It passed all the Jenkins automated build tests under mavericks, yosemite, and el capitan, fwiw.

Thanks!
