### ISSUE TITLE
Improved game usage instructions

### ISSUE THREAD

**Issue by mones** [smcameron/wordwarvi#7]
Hi,

I'm beginning to take care of Debian package maintenance of wordwarvi and noticed there's a bug in the BTS with a simple patch that could be interesting to add. You can see bug here:
https://bugs.debian.org/877993

And patch here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=877993;filename=wordwarvi-help.patch;msg=5

Note that I'm not the original author of the patch, so not making a pull-request to avoid undeserved credit.

best regards and thanks in advance.

**Comment by smcameron** [comment]
Applied as f13e271bda6f0235901f49a972f10a4b49423eff

**Comment by mones** [comment]
Thank you!
