### ISSUE TITLE
Fix cross-building

### ISSUE THREAD

**Issue by mones** [smcameron/wordwarvi#8]
Hi there,

Another patch to improve the ability to cross-build¹ wordwarvi.
Again, I'm not the original author, so not making a PR ;-)

Original bug: https://bugs.debian.org/943871
Link to patch: https://bugs.debian.org/cgi-bin/bugreport.cgi?att=1;bug=943871;filename=cross.patch;msg=5

Thanks!

¹ http://www.gnu.org/software/automake/manual/html_node/Cross_002dCompilation.html

**Comment by smcameron** [comment]
Applied as a7bf7f83b60306b22098ce1c5db938be1b5377c2

**Comment by mones** [comment]
Thanks, that was fast! :smiley:
