### ISSUE TITLE
Time to tag new release perhaps?

### ISSUE THREAD

**Issue by mones** [smcameron/wordwarvi#9]
Hi,

Not really an issue, but I'm wondering if perhaps it's time to tag current master as a new version so the world can enjoy latest fixes? ^_^

If not just ignore my suggestion and close this.

Best regards,

**Comment by smcameron** [comment]
Done: https://github.com/smcameron/wordwarvi/releases/tag/v1.0.3

**Comment by mones** [comment]
Thanks! :wink:
